### ISSUE TITLE
Request: Fix for kelmanwong's "New Gas and Liquid Filters" Mod

### ISSUE THREAD

**Issue by TroublesomeCorvid** [ttdly/Fix-ONI-Mods#1]
This was a great mod because it provided fool-proof filtering of materials based on temperature or germ presence.  The "vanilla" work around they provide is flawed in that if there is a power outage in your colony, it will allow unfiltered packets to pass through.

kelmanwong's Github repository:
https://github.com/kelmen/ONI-Mods

"New Gas and Liquid Filters" on Steam:
https://steamcommunity.com/sharedfiles/filedetails/?id=1854416020

**Comment by ttdly** [comment]
Ok, I'll have a try.

**Comment by ttdly** [comment]
@TroublesomeCorvid Sorry, I can't fix it.

The code is too messy and many methods have been deprecated.

**Comment by TroublesomeCorvid** [comment]
Thank you anyhow.
